name: changelog

on:
  workflow_call:

jobs:
  changelog:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5 # docs: https://github.com/TriPSs/conventional-changelog-action
        with:
          github-token: ${{ secrets.github_token }}
          git-user-name:  "Conventional Changelog Action"
          git-user-email: "3071062+changelog@users.noreply.github.com"
          skip-version-file: true
