name: changelog

on:
  workflow_call:

jobs:
  changelog:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: TriPSs/conventional-changelog-action@v5 # docs: https://github.com/TriPSs/conventional-changelog-action
        id: changelog
        with:
          github-token: ${{ secrets.github_token }}
          git-user-name:  "Conventional Changelog Action"
          git-user-email: "3071062+changelog@users.noreply.github.com"
          skip-version-file: true

      - uses: softprops/action-gh-release@v2 # docs: https://github.com/softprops/action-gh-release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.changelog.outputs.tag }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
