name: changelog

on:
  workflow_call:

jobs:
  changelog:

    runs-on: ubuntu-latest
  
    steps:
      - uses: TriPSs/conventional-changelog-action@v5 # docs: https://github.com/TriPSs/conventional-changelog-action
        with:
          github-token: ${{ secrets.github_token }}
