name: deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.repository != '99linesofcode/.github' }}

    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2 # docs: https://github.com/shivammathur/setup-php
        with:
          php-version: 8.2
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - run: composer install --no-interaction --no-progress --optimize-autoloader --classmap-authorative

      - run: |
          php artisan env:decrypt --key=${{ secrets.LARAVEL_DECRYPTION_KEY }}
          php artisan config:cache

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundle-cache: true

      - run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/setup-buildx-action@v3

      - run: kamal lock release -c "deploy.yml" && kamal redeploy -c "deploy.yml"
