name: deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.repository != '99linesofcode/.github' }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2 # docs: https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - run: composer install --no-dev --no-interaction --optimize-autoloader --classmap-authorative

      - run: |
          php artisan env:decrypt --key "${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}"
          php artisan config:cache
          php artisan event:cache
          php artisan route:cache
          php artisan view:cache
          php artisan tailwindcss:download
          php artisan tailwindcss:build --prod

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundle-cache: true

      - run: gem install kamal

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/setup-buildx-action@v3
        env:
          DOCKER_BUILDKIT: 1

      - run: |
          kamal lock release -c "deploy.yml"
          kamal redeploy -c "deploy.yml"
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
