name: deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      LARAVEL_ENV_ENCRYPTION_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2 # docs: https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - uses: ruby/setup-ruby@v1 # docs: https://github.com/ruby/setup-ruby
        with:
          ruby-version: head

      - uses: webfactory/ssh-agent@v0.9.0 # docs: https://github.com/webfactory/ssh-agent
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: docker/setup-buildx-action@v3 # docs: https://github.com/docker/setup-buildx-action
        env:
          DOCKER_BUILDKIT: 1

      - run: |
          composer install -n --prefer-dist --no-dev --no-progress --no-interaction
          php artisan env:decrypt --key ${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}
          gem install kamal
          kamal lock release -c "deployment/kamal.yml"
          kamal env push -c "deployment/kamal.yml"
          kamal deploy -c "deployment/deploy.yml"
